name = "brandme-api"
main = "src/worker/index.js"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
ADMIN_PASSWORD = "brandme-admin-2024"
CORS_ORIGIN = "*"


